<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ObYLjF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ObYLjF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2ObYLjF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2ObYLjF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2ObYLjF\App_KernelDevDebugContainer([
    'container.build_hash' => '2ObYLjF',
    'container.build_id' => 'dc70cc43',
    'container.build_time' => 1664040552,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ObYLjF');
