<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUbGkKUX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUbGkKUX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUbGkKUX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUbGkKUX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUbGkKUX\App_KernelDevDebugContainer([
    'container.build_hash' => 'UbGkKUX',
    'container.build_id' => '33c850d5',
    'container.build_time' => 1664041220,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUbGkKUX');
