<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGVpQG2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGVpQG2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGVpQG2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGVpQG2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGVpQG2\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGVpQG2',
    'container.build_id' => '08de5e3b',
    'container.build_time' => 1664041417,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGVpQG2');
